# Generated by Django 4.0.4 on 2022-06-14 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('name_en', models.TextField(max_length=255)),
                ('name_segment', models.TextField(max_length=255)),
                ('name_segment_en', models.TextField(max_length=255)),
                ('parsing_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новый проект', max_length=255, verbose_name='Короткое название проекта')),
                ('financing_type', models.PositiveSmallIntegerField(choices=[(0, 'проект капитальных расходов'), (1, 'IT-проект'), (2, 'проект НИОКР'), (3, 'проект без капитальных расходов')], null=True, verbose_name='Тип проекта')),
                ('currency_multiplication', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Не мультиплицирован'), (1, 'В тыс'), (2, 'В млн'), (3, 'В млрд'), (4, 'В трлн')], null=True, verbose_name='Мультипликатор денежного измерения')),
                ('time_detalization', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'По годам'), (1, 'По кварталам'), (2, 'По месяцам'), (3, 'По полугодиям')], default=0, null=True, verbose_name='Детализация проекта')),
                ('tax_model', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'минимальный'), (1, 'упрощенный'), (2, 'полный')], null=True, verbose_name='Вид моделирования налогов')),
                ('fin_source_equity', models.BooleanField(default=False, verbose_name='Использование собственного капитала в проекте')),
                ('fin_source_credit', models.BooleanField(default=False, verbose_name='Использование банковского кредита в проекте')),
                ('fin_source_leasing', models.BooleanField(default=False, verbose_name='Использование лизинга (финансовой аренды) в проекте')),
                ('comments', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления проекта')),
                ('active', models.BooleanField(default=True, verbose_name='Проект является активным в системе')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='айдишник автора проекта')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.currency', verbose_name='Валюта проекта')),
                ('industries', models.ManyToManyField(blank=True, related_name='industry_other', to='projects.industry')),
                ('industry_main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='industry_main', to='projects.industry')),
            ],
            options={
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('table', models.PositiveSmallIntegerField(choices=[(0, 'Вариант продаж'), (1, 'Вариант затрат'), (2, 'Вариант кап. расходов'), (3, 'Вариант налогов'), (4, 'Вариант ставки дисконтирования'), (5, 'Вариант собственного капитала')], default=0, verbose_name='Таблица, к которой относится вариант')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files')),
                ('file_type', models.PositiveSmallIntegerField(choices=[(0, 'Основной'), (1, 'Дополнительный')], verbose_name='Тип файла')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_init', models.DateField(blank=True, null=True, verbose_name='Планируемая дата регистрации предприятия')),
                ('name', models.CharField(max_length=255, verbose_name='Рабочее название предприятия')),
                ('company_sme', models.BooleanField(blank=True, null=True, verbose_name='Предприятие относится к разряду малого и среднего бизнеса')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_company', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('prefix', models.CharField(max_length=20)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.currency')),
            ],
        ),
        migrations.CreateModel(
            name='CopiedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типового проекта')),
                ('ext_switch', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ типового проекта другим пользователям организации')),
                ('finance_switch', models.BooleanField(blank=True, default=False, null=True, verbose_name='Сохранять финансовые данные в типовом проекте')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='copy_project', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalProjectInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_full', models.TextField(max_length=300, verbose_name='Полное название проекта')),
                ('user_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Пользовательский (внутренний) код проекта')),
                ('init_date', models.DateField(blank=True, null=True, verbose_name='Дата инициализации проекта')),
                ('contract', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер инвестиционного контракта')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Дата инвестиционного контракта')),
                ('full_name_person_responsible', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.country', verbose_name='Страна')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_project_information', to='projects.project')),
            ],
        ),
    ]
