# Generated by Django 4.0.4 on 2022-06-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalprojectinformation',
            name='name_full',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Полное название проекта'),
        ),
        migrations.AlterField(
            model_name='copiedproject',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название типового проекта'),
        ),
    ]
