# Generated by Django 4.0.4 on 2022-06-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_additionalprojectinformation_name_full_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('name_en', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='industry',
            name='name_segment',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='name_segment_en',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='parsing_text',
        ),
        migrations.AlterField(
            model_name='industry',
            name='name_en',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='segments',
            field=models.ManyToManyField(blank=True, to='projects.segment'),
        ),
    ]
