# Generated by Django 4.0.4 on 2022-06-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_segment_remove_industry_name_segment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='segments',
        ),
        migrations.RemoveField(
            model_name='project',
            name='industries',
        ),
        migrations.AddField(
            model_name='project',
            name='industry_segments',
            field=models.ManyToManyField(blank=True, to='projects.segment'),
        ),
    ]
