# Generated by Django 4.0.4 on 2022-06-16 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_remove_industry_segments_remove_project_industries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='industry_segments',
        ),
        migrations.AddField(
            model_name='segment',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.industry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Проект активен'),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='projects.currency', verbose_name='Валюта проекта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='currency_multiplication',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не мультиплицирован'), (1, 'В тыс'), (2, 'В млн'), (3, 'В млрд'), (4, 'В трлн')], default=1, verbose_name='Мультипликатор денежного измерения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='fin_source_equity',
            field=models.BooleanField(default=True, verbose_name='Использование собственного капитала в проекте'),
        ),
        migrations.AlterField(
            model_name='project',
            name='financing_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'проект капитальных расходов'), (1, 'IT-проект'), (2, 'проект НИОКР'), (3, 'проект без капитальных расходов')], default=0, null=True, verbose_name='Тип проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='industry_main',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='industry_main', to='projects.industry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='time_detalization',
            field=models.PositiveSmallIntegerField(choices=[(0, 'По годам'), (1, 'По кварталам'), (2, 'По месяцам'), (3, 'По полугодиям')], default=0, verbose_name='Детализация проекта'),
        ),
    ]
