# Generated by Django 4.0.4 on 2022-06-16 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_industry_segments_segment_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='projects.currency', verbose_name='Валюта проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='currency_multiplication',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не мультиплицирован'), (1, 'В тыс'), (2, 'В млн'), (3, 'В млрд'), (4, 'В трлн')], default=0, verbose_name='Мультипликатор денежного измерения'),
        ),
        migrations.AlterField(
            model_name='project',
            name='industry_main',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='industry_main', to='projects.industry'),
        ),
    ]
