# Generated by Django 4.0.4 on 2022-06-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_currency_alter_project_industry_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='table',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Вариант продаж'), (1, 'Вариант затрат'), (2, 'Вариант кап. расходов'), (3, 'Вариант налогов'), (4, 'Вариант ставки дисконтирования'), (5, 'Вариант собственного капитала'), (6, 'Вариант банковского кредита'), (7, 'Вариант лизинга')], default=0, verbose_name='Таблица, к которой относится вариант'),
        ),
    ]
