# Generated by Django 4.0.4 on 2022-06-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tax_model',
        ),
        migrations.AddField(
            model_name='project',
            name='industry_segments',
            field=models.ManyToManyField(blank=True, to='projects.segment'),
        ),
    ]
