# Generated by Django 4.0.4 on 2022-07-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_project_tax_model_project_industry_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='copied_project',
            field=models.BooleanField(default=False, verbose_name='Проект является типовым'),
        ),
    ]
