# Generated by Django 4.0.4 on 2022-07-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_copied_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='copied_project',
        ),
        migrations.AddField(
            model_name='copiedproject',
            name='copied_project',
            field=models.BooleanField(default=False, verbose_name='Проект является типовым'),
        ),
    ]
