# Generated by Django 4.0.4 on 2022-07-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_copied_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalprojectinformation',
            name='contract_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата инвестиционного контракта'),
        ),
        migrations.AlterField(
            model_name='additionalprojectinformation',
            name='init_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата инициализации проекта'),
        ),
        migrations.AlterField(
            model_name='projectcompany',
            name='date_init',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Планируемая дата регистрации предприятия'),
        ),
    ]
