# Generated by Django 4.0.4 on 2022-07-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_variant_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to='project_files/%Y/%m/%d/%H:%M:%S'),
        ),
    ]
