# Generated by Django 4.0.4 on 2022-07-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_variant_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='project',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='table',
        ),
    ]
