# Generated by Django 4.0.4 on 2022-07-28 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_delete_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalprojectinformation',
            name='contract_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 18, 10, 52, 906171), verbose_name='Дата инвестиционного контракта'),
        ),
        migrations.AlterField(
            model_name='additionalprojectinformation',
            name='init_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 18, 10, 52, 906136), verbose_name='Дата инициализации проекта'),
        ),
        migrations.AlterField(
            model_name='projectcompany',
            name='date_init',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 18, 10, 52, 907102), verbose_name='Планируемая дата регистрации предприятия'),
        ),
    ]
