# Generated by Django 4.0.4 on 2022-07-28 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_additionalprojectinformation_contract_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalprojectinformation',
            name='contract_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата инвестиционного контракта'),
        ),
        migrations.AlterField(
            model_name='additionalprojectinformation',
            name='init_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата инициализации проекта'),
        ),
        migrations.AlterField(
            model_name='projectcompany',
            name='date_init',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Планируемая дата регистрации предприятия'),
        ),
    ]
