# Generated by Django 4.0.4 on 2022-07-23 12:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0020_delete_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(default='Новый вариант', max_length=255)),
                ('product_name', models.TextField(default='Новый продукт', verbose_name='Названия продукции, товаров, услуг')),
                ('product_unit', models.PositiveSmallIntegerField(choices=[(0, 'шт.'), (1, 'компл.'), (2, 'ящ.'), (3, 'тн.'), (4, 'ед.'), (5, 'м3'), (6, 'Баррель'), (7, 'МВт'), (8, 'Гкал'), (9, 'усл.')], default=0, verbose_name='применяемая единица измерения продукта')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала продаж')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания продаж')),
                ('duration', models.CharField(default='0 лет 0 месяцев 0 дней', max_length=255, verbose_name='Длительность')),
                ('sales_volume', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='объем продаж в единицах продаж до расчета сезонности и индексации')),
                ('VAT', models.PositiveSmallIntegerField(choices=[(0, 'Не облагается'), (1, '0'), (2, '10'), (3, '20')], default=0, verbose_name='Ставка НДС')),
                ('NDPI', models.BooleanField(default=False, verbose_name='Облагается НДПИ')),
                ('excise_duty', models.BooleanField(default=False, verbose_name='Облагается акцизом')),
                ('value_indexation_period', models.PositiveSmallIntegerField(choices=[(0, 'По годам'), (1, 'По кварталам'), (2, 'По месяцам')], default=0, verbose_name='Частота индексации объема')),
                ('value_indexation', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Значение индексации объема')),
                ('inflation_indexation_period', models.PositiveSmallIntegerField(choices=[(0, 'По годам'), (1, 'По кварталам'), (2, 'По месяцам')], default=0, verbose_name='Частота индексации цены на инфляцию')),
                ('inflation_indexation', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Коэффициент индексации на инфляцию')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена продукции')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='OpexVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(default='Новый вариант', max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Opex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Новый расход', max_length=350, verbose_name='Пользовательское название расхода')),
                ('cost_types_by_economic_grouping', models.PositiveSmallIntegerField(choices=[(0, 'Материальные затраты'), (1, 'Товары'), (2, 'Заработная плата'), (3, 'Социальное обеспечение и социальные налоги'), (4, 'Амортизация'), (5, 'Прочие производственные расходы'), (6, 'Арендные расходы'), (7, 'Налоговые расходы'), (8, 'Коммерческие расходы'), (9, 'Управленческие расходы'), (10, 'Прочие расходы')], default=0, verbose_name='Выбор типа затрат по экономической группировке')),
                ('types_business_activity_costs', models.PositiveSmallIntegerField(choices=[(0, 'Постоянные расходы'), (1, 'Переменные расходы')], default=0, verbose_name='Выбор типа затрат по деловой активности')),
                ('fixed_asset_lease_payment', models.BooleanField(default=False, verbose_name='Идентификатор операционной аренды')),
                ('tax', models.BooleanField(default=False, verbose_name='Идентификатор налогового платежа в составе расходов')),
                ('type_tax', models.BooleanField(default=True, verbose_name='Включать расход в расчет налога на прибыль')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма с НДС в месяц, рублей')),
                ('VAT_rate', models.PositiveSmallIntegerField(choices=[(0, 'Не облагается'), (1, '0'), (2, '10'), (3, '20')], default=0, verbose_name='Ставка НДС')),
                ('price_indexation', models.BooleanField(default=False, verbose_name='Индексация закупочной цены по продажам')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opexs', to='project_sales.opexvariant')),
            ],
        ),
    ]
