# Generated by Django 4.0.4 on 2022-07-28 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinit',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 18, 10, 52, 920563), verbose_name='Дата окончания продаж'),
        ),
        migrations.AlterField(
            model_name='salesinit',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 18, 10, 52, 920544), verbose_name='Дата начала продаж'),
        ),
    ]
