# Generated by Django 4.0.4 on 2022-07-28 18:21

from django.db import migrations, models
import django.utils.timezone
import project_sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_sales', '0002_alter_salesinit_end_date_alter_salesinit_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinit',
            name='end_date',
            field=models.DateTimeField(default=project_sales.models.next_month, verbose_name='Дата окончания продаж'),
        ),
        migrations.AlterField(
            model_name='salesinit',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала продаж'),
        ),
    ]
