# Generated by Django 4.0.4 on 2022-07-28 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_sales', '0003_alter_salesinit_end_date_alter_salesinit_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinit',
            name='duration',
        ),
        migrations.AlterField(
            model_name='salesinit',
            name='inflation_indexation',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Коэффициент индексации на инфляцию'),
        ),
    ]
