# Generated by Django 4.0.4 on 2022-07-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_sales', '0004_remove_salesinit_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinit',
            name='inflation_indexation_period',
            field=models.PositiveSmallIntegerField(choices=[(0, 'По годам'), (1, 'По кварталам'), (2, 'По месяцам'), (3, 'По полугодиям')], default=0, verbose_name='Частота индексации цены на инфляцию'),
        ),
        migrations.AlterField(
            model_name='salesinit',
            name='value_indexation_period',
            field=models.PositiveSmallIntegerField(choices=[(0, 'По годам'), (1, 'По кварталам'), (2, 'По месяцам'), (3, 'По полугодиям')], default=0, verbose_name='Частота индексации объема'),
        ),
    ]
