# Generated by Django 4.0.4 on 2022-07-28 18:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_financing_sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 18, 10, 52, 912758), verbose_name='Дата договора'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='date_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 18, 10, 52, 912788), verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='leasingcontract',
            name='contract_start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 18, 10, 52, 913795), verbose_name='Дата договора'),
        ),
        migrations.AlterField(
            model_name='leasingcontract',
            name='date_planned_accounting_object',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 18, 10, 52, 913765), verbose_name='Дата планового учета объекта'),
        ),
        migrations.AlterField(
            model_name='leasingcontract',
            name='initial_payment',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)], verbose_name='Доля первоначального взноса'),
        ),
        migrations.AlterField(
            model_name='ownfund',
            name='source_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 18, 10, 52, 911902), verbose_name='Дата вложения собственных средств'),
        ),
    ]
