# Generated by Django 4.0.4 on 2022-07-28 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_financing_sources', '0002_alter_credit_date_alter_credit_date_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата договора'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='date_in',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='leasingcontract',
            name='contract_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата договора'),
        ),
        migrations.AlterField(
            model_name='leasingcontract',
            name='date_planned_accounting_object',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата планового учета объекта'),
        ),
        migrations.AlterField(
            model_name='ownfund',
            name='source_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата вложения собственных средств'),
        ),
    ]
