# Generated by Django 4.0.4 on 2022-07-23 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_financing_sources', '0001_initial'),
        ('project_economic_indicators', '0001_initial'),
        ('projects', '0020_delete_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_annual_revenue', models.FloatField(verbose_name='Среднегодовая выручка (без НДС), Руб')),
                ('average_annual_operating_costs', models.FloatField(verbose_name='Среднегодовые операционные затраты с амортизайцией (без НДС), руб')),
                ('average_annual_net_profit', models.FloatField(verbose_name='Среднегодовая чистая прибыль, руб')),
                ('average_return_on_sales', models.FloatField(verbose_name='Средняя рентабельность продаж, %')),
                ('average_annual_VAT', models.FloatField(verbose_name='Среднегодовой НДС, руб')),
                ('average_annual_income_tax', models.FloatField(verbose_name='Среднегодовой налог на прибыль, руб')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Месяц, к которому относятся значения')),
                ('fixed_assets', models.FloatField(verbose_name='Основные средства')),
                ('Total_non_current_assets', models.FloatField(verbose_name='Итого внеоборотные активы')),
                ('Stocks', models.FloatField(verbose_name='Запасы')),
                ('accounts_receivable', models.FloatField(verbose_name='Дебиторская задолженность')),
                ('cash', models.FloatField(verbose_name='Денежные средства')),
                ('total_current_assets', models.FloatField(verbose_name='Итого оборотные активы')),
                ('total_balance', models.FloatField(verbose_name='Итого баланс')),
                ('authorized_share_capital', models.FloatField(verbose_name='Уставный (акционерный) капитал')),
                ('undestributed_profits', models.FloatField(verbose_name='Нераспределенная прибыль')),
                ('total_equity', models.FloatField(verbose_name='Итого собственный капитал')),
                ('borrowed_funds', models.FloatField(verbose_name='Заемные средства')),
                ('accounts_payable', models.FloatField(verbose_name='Кредиторская задолженность')),
                ('total_liabilities', models.FloatField(verbose_name='Итого обязательства')),
                ('Total_balance2', models.FloatField(verbose_name='Итого баланс')),
            ],
        ),
        migrations.CreateModel(
            name='BasicIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_rate', models.FloatField(verbose_name='ставка дисконтирования, %')),
                ('refinancing_rate', models.FloatField(verbose_name='ставка рефинансирования, %')),
                ('net_present_value_npv', models.FloatField(verbose_name='чистая приведенная стоимость npv, руб')),
                ('profitability_index_pi', models.FloatField(verbose_name='индекс рентабельности pi')),
                ('internal_rate_return_irr', models.FloatField(verbose_name='внутренняя норма доходности irr, %')),
                ('MIRR_internal_rate_return', models.FloatField(verbose_name='Модифицированная внутренняя норма доходности MIRR, %')),
            ],
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='projects.project')),
                ('variant_capex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_capex', to='project_economic_indicators.capex', verbose_name='Вариант кап. расходов')),
                ('variant_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_credit', to='project_financing_sources.creditvariant', verbose_name='Вариант банковского кредита')),
            ],
        ),
        migrations.CreateModel(
            name='ResultFinancialAnalys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Месяц, к которому относятся значения')),
                ('return_on_sales_rot', models.FloatField(verbose_name='Рентабельность продаж (ROS)')),
                ('return_on_equity_roe', models.FloatField(verbose_name='Рентабельность собственного капитала (ROE)')),
                ('return_on_assets_roa', models.FloatField(verbose_name='Рентабельность активов (ROA)')),
                ('asset_turnover_ratio', models.FloatField(verbose_name='Коэффициент оборачиваемости активов')),
                ('сurrent_assets_turnover_ratio', models.FloatField(verbose_name='Коэффициент оборачиваемости оборотных активов')),
                ('inventory_turnover_ratio', models.FloatField(verbose_name='Коэффициент оборачиваемости запасов')),
                ('accounts_receivable_turnover_ratio', models.FloatField(verbose_name='Коэффициент оборачиваемости дебиторской задолженности')),
                ('accounts_payable_turnover_ratio', models.FloatField(verbose_name='Коэффициент оборачиваемости кредиторской задолженности')),
                ('autonomy_coefficient', models.FloatField(verbose_name='Коэффициент автономии')),
                ('leverage_ratio_de', models.FloatField(verbose_name='Коэффициент левериджа (D/E)')),
                ('own_working_capital_ratio', models.FloatField(verbose_name='Коэффициент собственных оборотных средств')),
                ('absolute_liquidity_ratio', models.FloatField(verbose_name='Коэффициент абсолютной ликвидности')),
                ('interim_liquidity_ratio', models.FloatField(verbose_name='Коэффициент промежуточной ликвидности')),
                ('current_liquidity_ratio', models.FloatField(verbose_name='Коэффициент текущей ликвидности')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_calculations.calculation')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitAndLossPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Месяц, к которому относятся значения')),
                ('revenue', models.FloatField(verbose_name='Выручка')),
                ('сost_price', models.FloatField(verbose_name='Себестоимость')),
                ('gross_profit', models.FloatField(verbose_name='Валовая прибыль')),
                ('business_expenses', models.FloatField(verbose_name='Коммерческие расходы')),
                ('management_expenses', models.FloatField(verbose_name='Управленческие расходы')),
                ('operating_income_ebit', models.FloatField(verbose_name='Операционная прибыль EBIT')),
                ('interest_expenses', models.FloatField(verbose_name='Процентные расходы')),
                ('profit_before_tax', models.FloatField(verbose_name='Прибыль до налогообложения')),
                ('income_tax', models.FloatField(verbose_name='Налог на прибыль')),
                ('net_profit', models.FloatField(verbose_name='Чистая прибыль')),
                ('ebitda', models.FloatField(verbose_name='EBITDA')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_calculations.calculation')),
            ],
        ),
        migrations.CreateModel(
            name='PaybackProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal_payback_period', models.DateField(verbose_name='Номинальный срок окупаемости')),
                ('discounted_payback_period', models.DateField(verbose_name='Дисконтированный срок окупаемости')),
                ('calculation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_calculations.calculation')),
            ],
        ),
        migrations.CreateModel(
            name='MainParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DateField(blank=True, verbose_name='Длительность проекта')),
                ('start_date', models.DateField(verbose_name='Начало проекта')),
                ('end_date', models.DateField(verbose_name='Окончание проекта')),
                ('rating', models.PositiveIntegerField(verbose_name='Рейтинг проекта')),
                ('calculation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_calculations.calculation')),
            ],
        ),
        migrations.CreateModel(
            name='FundingAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capEx_amount', models.FloatField(verbose_name='Сумма CapEx (с НДС), руб')),
                ('amount_of_own_funds', models.FloatField(verbose_name='Сумма собственных средств, руб')),
                ('amount_of_borrowed_funds', models.FloatField(verbose_name='Сумма заемных средств, руб')),
                ('DE_ratio', models.FloatField(verbose_name='Коэффициент D/E')),
                ('average_Debt_EBITDA_ratio', models.FloatField(verbose_name='Средний коэффициент Debt/EBITDA')),
                ('calculation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_calculations.calculation')),
            ],
        ),
        migrations.CreateModel(
            name='CashFlowPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Месяц, к которому относятся значения')),
                ('EBITDA', models.FloatField(verbose_name='EBITDA')),
                ('working_weight_change', models.FloatField(verbose_name='Изменение рабочего капитала')),
                ('income_tax', models.FloatField(verbose_name='Налог на прибыль')),
                ('net_cash_flow_from_operations', models.FloatField(verbose_name='Чистый денежный поток по операционной деятельности')),
                ('payment_capital_costs', models.FloatField(verbose_name='Оплата капитальных расходов')),
                ('VAT_refund', models.FloatField(verbose_name='Возмещение НДС')),
                ('payment_liquidation_expenses', models.FloatField(verbose_name='Оплата ликвидационных расходов')),
                ('receipt_liquidation_proceeds', models.FloatField(verbose_name='Поступление ликвидационных доходов')),
                ('net_cash_flow_from_investing_activities', models.FloatField(verbose_name='Чистый денежный поток по инвестиционной деятельности')),
                ('receipt_from_owners', models.FloatField(verbose_name='Поступление от собственников')),
                ('credit_receipt', models.FloatField(verbose_name='Поступление кредита')),
                ('return_credits', models.FloatField(verbose_name='Возврат кредитов')),
                ('loan_repayment', models.FloatField(verbose_name='Погашение кредита')),
                ('interest_payment', models.FloatField(verbose_name='Оплата процентов')),
                ('net_cash_flow_from_financing_activities', models.FloatField(verbose_name='Чистый денежный поток по финансовой деятельности')),
                ('net_cash_flow', models.FloatField(verbose_name='Чистый денежный поток')),
                ('cash_balance_beginning_period', models.FloatField(verbose_name='Остаток денежных средств на начало периода')),
                ('cash_balance_the_end_period', models.FloatField(verbose_name='Остаток денежных средств на конец периода')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_calculations.calculation')),
            ],
        ),
    ]
