# Generated by Django 4.0.4 on 2022-08-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_calculations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profitandlossplan',
            old_name='сost_price',
            new_name='cost_price',
        ),
        migrations.RenameField(
            model_name='resultfinancialanalys',
            old_name='сurrent_assets_turnover_ratio',
            new_name='current_assets_turnover_ratio',
        ),
    ]
