# Generated by Django 4.0.4 on 2022-07-23 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_sales', '0001_initial'),
        ('project_financing_sources', '0001_initial'),
        ('project_calculations', '0001_initial'),
        ('project_taxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='variant_discount_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_discount_rates', to='project_taxes.discountrate', verbose_name='Вариант ставки дисконтирования'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='variant_leasing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_leasing', to='project_financing_sources.leasingcontractvariant', verbose_name='Вариант лизинга'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='variant_opex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_costs', to='project_sales.opexvariant', verbose_name='Вариант затрат'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='variant_own_fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_own_fund', to='project_financing_sources.ownfundvariant', verbose_name='Вариант собственного капитала'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='variant_sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_sales', to='project_sales.salesinit', verbose_name='Вариант продаж'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='variant_taxs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_taxs', to='project_taxes.taxprm', verbose_name='Вариант налогов'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='variant_wk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_wk', to='project_financing_sources.workingcapitalparameter', verbose_name='Вариант рабочего капитала'),
        ),
        migrations.AddField(
            model_name='basicindicator',
            name='calculation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_calculations.calculation'),
        ),
        migrations.AddField(
            model_name='balance',
            name='calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_calculations.calculation'),
        ),
        migrations.AddField(
            model_name='annualaverage',
            name='calculation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_calculations.calculation'),
        ),
    ]
