# Generated by Django 4.0.4 on 2022-07-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_calculations', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculation',
            old_name='variant_credit',
            new_name='variant_credits',
        ),
        migrations.RenameField(
            model_name='calculation',
            old_name='variant_opex',
            new_name='variant_opexs',
        ),
        migrations.RenameField(
            model_name='calculation',
            old_name='variant_own_fund',
            new_name='variant_own_funds',
        ),
    ]
