# Generated by Django 4.0.4 on 2022-07-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_calculations', '0003_rename_variant_credit_calculation_variant_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='month',
            field=models.DateTimeField(verbose_name='Месяц, к которому относятся значения'),
        ),
        migrations.AlterField(
            model_name='cashflowplan',
            name='month',
            field=models.DateTimeField(verbose_name='Месяц, к которому относятся значения'),
        ),
        migrations.AlterField(
            model_name='mainparameter',
            name='duration',
            field=models.DateTimeField(blank=True, verbose_name='Длительность проекта'),
        ),
        migrations.AlterField(
            model_name='profitandlossplan',
            name='month',
            field=models.DateTimeField(verbose_name='Месяц, к которому относятся значения'),
        ),
        migrations.AlterField(
            model_name='resultfinancialanalys',
            name='month',
            field=models.DateTimeField(verbose_name='Месяц, к которому относятся значения'),
        ),
    ]
