# Generated by Django 4.0.4 on 2022-08-02 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_taxes', '0002_alter_taxprm_tax_min_burden'),
        ('project_sales', '0005_alter_salesinit_inflation_indexation_period_and_more'),
        ('project_financing_sources', '0003_alter_credit_date_alter_credit_date_in_and_more'),
        ('project_economic_indicators', '0005_alter_capex_liquidation_cost_vat_rate_and_more'),
        ('project_calculations', '0005_rating_remove_mainparameter_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='variant_capex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_capex', to='project_economic_indicators.capex', verbose_name='Вариант кап. расходов'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='variant_credits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_credit', to='project_financing_sources.creditvariant', verbose_name='Вариант банковского кредита'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='variant_discount_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_discount_rates', to='project_taxes.discountrate', verbose_name='Вариант ставки дисконтирования'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='variant_leasing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_leasing', to='project_financing_sources.leasingcontractvariant', verbose_name='Вариант лизинга'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='variant_opexs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_costs', to='project_sales.opexvariant', verbose_name='Вариант затрат'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='variant_own_funds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_own_fund', to='project_financing_sources.ownfundvariant', verbose_name='Вариант собственного капитала'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='variant_sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_sales', to='project_sales.salesinit', verbose_name='Вариант продаж'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='variant_taxs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_taxs', to='project_taxes.taxprm', verbose_name='Вариант налогов'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='variant_wk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_wk', to='project_financing_sources.workingcapitalparameter', verbose_name='Вариант рабочего капитала'),
        ),
    ]
