# Generated by Django 4.0.4 on 2022-08-03 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_calculations', '0006_alter_calculation_variant_capex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainparameter',
            name='duration',
        ),
        migrations.AddField(
            model_name='rating',
            name='calculation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='project_calculations.calculation'),
            preserve_default=False,
        ),
    ]
