from django.urls import path
from . import views

urlpatterns = [
	path('own_funds_variants/',
		views.OwnFundVariantCreateView.as_view(),
		name='own_funds_variants_list'),
	path('own_funds_variants/copy/<pk>/',
		views.OwnFundVariantCopyView.as_view(),
		name='own_funds_variant_detail'),
	path('own_funds_variants/<pk>/',
		views.OwnFundVariantDetailView.as_view(),
		name='own_funds_variant_detail'),

	path('own_funds/',
		views.OwnFundListView.as_view(),
		name='own_funds_list'),
	path('own_funds/copy/<pk>/',
		views.OwnFundCopyView.as_view(),
		name='own_funds_list'),
	path('own_funds/<pk>/',
		views.OwnFundDetailView.as_view(),
		name='own_fund_detail'),

	path('credits_variants/',
		views.CreditVariantCreateView.as_view(),
		name='credits_variants_list'),
	path('credits_variants/copy/<pk>/',
		views.CreditVariantCopyView.as_view(),
		name='credits_variants_copy'),
	path('credits_variants/<pk>/',
		views.CreditVariantDetailView.as_view(),
		name='credits_variants_detail'),

	path('credits/enums/',
		views.CreditEnums.as_view(),
		name='credits_enums'),
	path('credits/',
		views.CreditsListView.as_view(),
		name='credits_list'),
	path('credits/copy/<pk>/',
		views.CreditCopyView.as_view(),
		name='credit_copy'),
	path('credits/<pk>/',
		views.CreditDetailView.as_view(),
		name='credit_detail'),

	path('leasings_variants/',
		views.LeasingVariantCreateView.as_view(),
		name='leasings_variants_list'),
	path('leasings_variants/copy/<pk>/',
		views.LeasingVariantCopyView.as_view(),
		name='leasings_variants_copy'),
	path('leasings_variants/<pk>/',
		views.LeasingVariantDetailView.as_view(),
		name='leasings_variants_detail'),

	path('leasings/enums/',
		views.LeasingEnums.as_view(),
		name='leasings_enums'),
	path('leasings/',
		views.LeasingListView.as_view(),
		name='leasings_list'),
	path('leasings/copy/<pk>/',
		views.LeasingCopyView.as_view(),
		name='leasing_copy'),
	path('leasings/<pk>/',
		views.LeasingDetailView.as_view(),
		name='leasing_detail'),

	path('working_capital_parameters/',
		views.WorkingCapitalParameterListView.as_view(),
		name='working_capital_parameters_list'),
	path('working_capital_parameters/copy/<pk>/',
		views.WorkingCapitalParameterCopyView.as_view(),
		name='working_capital_parameter_detail'),
	path('working_capital_parameters/<pk>/',
		views.WorkingCapitalParameterDetailView.as_view(),
		name='working_capital_parameter_detail'),
]
