# Generated by Django 4.0.4 on 2022-07-28 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_taxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxprm',
            name='tax_min_burden',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Налоговая нагрузка'),
        ),
    ]
