# Generated by Django 4.0.4 on 2022-07-28 18:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_economic_indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capex',
            name='amount_capital_expenditure',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма капитальных расходов с НДС'),
        ),
        migrations.AlterField(
            model_name='capex',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 18, 10, 52, 909200), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='capex',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 18, 10, 52, 909182), verbose_name='Дата начала'),
        ),
    ]
