# Generated by Django 4.0.4 on 2022-07-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_economic_indicators', '0003_alter_capex_end_date_alter_capex_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capex',
            name='duration',
        ),
    ]
